### ISSUE TITLE
Missing input for api key since 2018-03-16

### ISSUE THREAD

**Issue by blar** [mxschmitt/ui-driver-hetzner#6]
Cannot add new hosts, because the input field for the api key is missing.

![bildschirmfoto 2018-03-16 um 12 38 53](https://user-images.githubusercontent.com/111508/37518824-216ed8c2-2917-11e8-8400-a14c2538f183.png)

**Comment by thbiela** [comment]
+1

**Comment by mxschmitt** [comment]
Known bug i will fix this ASAP (in 1-2hours) sorry!

**Comment by mxschmitt** [comment]
Okay, I fixed it. Sorry...

**Comment by thbiela** [comment]
Hm, still not working. I deleted the driver and reinstalled it. Maybe it's because you put the new dist folder inside dist-v2?

**Comment by mxschmitt** [comment]
@thbiela please recheck

**Comment by thbiela** [comment]
Unfortunately, it does not work. I deleted the driver and reinstalled without success. I use the catalog item. Could this be some caching issue?

**Comment by mxschmitt** [comment]
yep, try to use another browser or clear simply your cache (i use the chrome devtools and check there in the settings "disable cache while dev tools are open")

**Comment by thbiela** [comment]
Works after server reboot. Thank you very much for this great support! 👍

**Comment by mxschmitt** [comment]
No Problem, i rework the "deployment" of the source files currently. Then I'm using gce instead of gh pages to deploy the component.js. :)
